# Generated by Django 3.2.8 on 2021-10-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakelevel',
            name='level',
        ),
        migrations.AddField(
            model_name='cakelevel',
            name='level_num',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='число уровней торта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='berry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='berry',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.cakelevel', verbose_name='число уровней'),
        ),
        migrations.AlterField(
            model_name='cakeform',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='cakeform',
            name='type',
            field=models.CharField(max_length=100, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='cakelevel',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='decor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='decor',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cake',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.cake', verbose_name='торт'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='цена'),
        ),
    ]
